#!/bin/bash

# Get directory where this script is                                                                               
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Import config
source "$DIR/config"

# Get pub keys from array $RECIPIENTS
if [ ! -z "$RECIPIENTS" ]
then
    SRES=""
    for ix in ${!RECIPIENTS[*]}
    do
        pubkey="${RECIPIENTS[$ix]}"
        if gpg --list-keys "$pubkey" > /dev/null
        then
            SRES+=" -r $pubkey"
        fi
    done
    if [ -z "$SRES" ]
    then
       echo "No valid pubkey names found in \$RECIPIENTS array in /root/config"
       exit
    fi
else
    echo "Specify array of \$RECIPIENTS - gpg pub keys in /root/config"
    exit
fi

# Get list of hypervisors
if [ -z "$HYPERVISORS" ]
then
    echo "Specify list of \$HYPERVISORS in /root/config"
    exit
fi

# Try to mount dst disk
if mount LABEL="ARC1" /root/dst
then
    echo "Mounted ARC1 destination disk"
else
    if mount LABEL="ARC2" /root/dst
    then
        echo "Mounted ARC2 destination disk"
    else
        echo "Destination disk ARC1 or ARC2 not found!"
        exit
    fi
fi

for HV in $HYPERVISORS
do
    if mount LABEL="$HV" /root/src
    then
        echo "Mount partition with label $HV."
        if [ -d /root/src/$HV ]
        then
            if [ -d /root/dst/$HV ]
            then
                # If directory exists, then delete all files inside it.
                rm /root/dst/$HV/*
            else
                mkdir /root/dst/$HV
            fi

            for FL in /root/src/$HV/*
            do
                # Cypher files
                echo $FL
                gpg --compress-algo none $SRES -v -o "/root/dst/$HV/$(basename $FL).gpg" -e "$FL" 

            done
        else
            echo "Source directory /root/src/$HV not found!"
        fi

        umount /root/src
    else
        echo "Partition with label $HV not found."
    fi

done

umount /root/dst

