#!/bin/bash

source /root/config

if [ "$1" == "--no-sms" ]
then
    NOSMS=1
fi

FNAME=$(hostname)_$(date +%Y%m%d)

xe pool-dump-database file-name=${FNAME}.pool

xe host-backup name-label=$(hostname) file-name=${FNAME}.host

tar czpvf ${FNAME}.conf.tar.gz \
    /root/vm-backup \
    /root/host-backup \
    /root/sms_sms.ru \
	/root/update \
	/root/config \
	/etc/sysconfig/modules/* \
	/etc/sysconfig/iptables \
    /etc/mdadm.conf \
    /etc/ups/* \
    /etc/ssmtp/* \
    /etc/zabbix/* \
    /etc/rc.d/rc.local \
	/etc/cron.*/*

xe host-restore name-label=$(hostname) file-name=${FNAME}.host

MSG="Host ${FNAME} backup complete."

if [ -z "$NOSMS" ]
then
    # There was no --no-sms option, let's send sms
    /root/sms_sms.ru ${PHONE} "$MSG"
else
    echo $MSG
fi

