#!/bin/bash

# Get directory where this script is                                                                               
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Import config
source "$DIR/config"

if [ "$1" == "--no-sms" ]
then
    NOSMS=1
fi

FNAME=$(hostname)_$(date +%Y%m%d)

xe pool-dump-database file-name=${FNAME}.pool

xe host-backup name-label=$(hostname) file-name=${FNAME}.host

tar czpf ${FNAME}.conf.tar.gz \
    /root/vm-backup \
    /root/host-backup \
    /root/sms_sms.ru \
	/root/update \
	/root/config \
	/etc/sysconfig/modules/* \
	/etc/sysconfig/iptables \
    /etc/mdadm.conf \
    /etc/ups/* \
    /etc/ssmtp/* \
    /etc/zabbix/* \
    /etc/rc.d/rc.local \
	/etc/cron.*/*

xe host-restore name-label=$(hostname) file-name=${FNAME}.host

MSG="Host ${FNAME} backup complete."

if [ -z "$NOSMS" ]
then
    # There was no --no-sms option, let's send sms
    /root/sms_sms.ru ${PHONE} "$MSG"
else
    echo $MSG
fi

