#!/bin/bash

# You need to open TCP port $NETCAT_PORT on your firewall.
#
# Add lines to open port 8080 to /etc/sysconfig/iptables
#    # netcat for backups
#    -A RH-Firewall-1-INPUT -m conntrack --ctstate NEW -m tcp -p tcp --dport 8080 -j ACCEPT
#
# then restart iptables:
#    systemctl restart iptables

# If your system do not have ncat, install it
#    yum install nmap-ncat

# Get directory where this script is                                                                               
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Import config
source "$DIR/config"

if [ -z "$NETCAT_PORT" ]
then
    echo "Set NETCAT_PORT variable in $DIR/config"
    exit
fi

if [ -z "$ADMIN_EMAIL" ]
then
    echo "Set ADMIN_EMAIL variable in $DIR/config"
    exit
fi

# Get pub keys from array $RECIPIENTS and put to $RES list acceptable by gpg
if [ ! -z "$RECIPIENTS" ]
then
    SRES=""
    for ix in ${!RECIPIENTS[*]}
    do
        pubkey="${RECIPIENTS[$ix]}"
        if gpg --list-keys "$pubkey" > /dev/null
        then
            SRES+=" -r $pubkey"
        fi
    done
    if [ -z "$SRES" ]
    then
       echo "No valid pubkey names found in \$RECIPIENTS array in /root/config"
       exit
    fi
else
    echo "Specify array of \$RECIPIENTS - gpg pub keys in /root/config"
    exit
fi

# Get list of files
FILES=$(nc -l $NETCAT_PORT)

for fname in $FILES
do
  sleep 2s
  (nc -l $NETCAT_PORT | gpg $SRES -e -o ${fname}.gpg) && (echo "Job done" | mail -s "Done $fname ($(stat -c '%s' ${fname}.gpg | numfmt --to=iec))" ${ADMIN_EMAIL})
done

DIR=$(basename $(pwd))
echo "Group job done at $DIR" | mail -s "$DIR - group done" ${ADMIN_EMAIL}

