#!/bin/bash

# If your system do not have ncat, install it
#    yum install nmap-ncat

# Get directory where this script is                                                                               
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Import config
source "$DIR/config"

if [ -z "$NETCAT_ADDR" ]
then
    echo "Set NETCAT_ADDR variable in $DIR/config"
    exit
fi

if [ -z "$NETCAT_PORT" ]
then
    echo "Set NETCAT_PORT variable in $DIR/config"
    exit
fi

FILES=$*

sleep 5s
echo $FILES | nc $NETCAT_ADDR $NETCAT_PORT

for f in $FILES
do
  sleep 5s
  nc $NETCAT_ADDR $NETCAT_PORT < $f
  echo "Done $f"
done

