#!/bin/bash
URL=https://github.com/ruslan-ohitin/xenserver-scripts/archive/master.zip

wget --no-verbose -O new_version.zip $URL 

unzip -q -j -o new_version.zip  

chmod +x host-backup sms_sms.ru update vm-backup xsupdate copy-backups weekly-vm-backup

rm -f new_version.zip
