#!/bin/bash

# Backup VMs weekly

source /root/config

if [ ! -z "$VMS_TO_BACKUP" ]
then
    if mount LABEL="$(hostname)" /root/usb-hdd
    then
        if [ ! -d /root/usb-hdd/$(hostname) ]
        then
            mkdir /root/usb-hdd/$(hostname)
        fi
        cd /root/usb-hdd/$(hostname)
        rm -f *
        
        /root/host-backup
        /root/vm-backup $VMS_TO_BACKUP
        cd /root

        umount /root/usb-hdd
    else
        echo "Unabel to mount partition with label $(hostname)"
    fi    
else
    echo "Set variable VMS_TO_BACKUP to list of VMs"    
fi    
