#!/bin/bash

# Backup VMs weekly
echo "Subject: $0 host: $(hostname) date: $(date +%Y-%m-%d)"

# Get directory where this script is                                                                               
# https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Import config
source "$DIR/config"

if [ ! -z "$VMS_TO_BACKUP" ]
then
    if mount LABEL="$(hostname)" /root/usb-hdd
    then
        echo "Partition mounted"

        if [ ! -d /root/usb-hdd/$(hostname) ]
        then
            mkdir /root/usb-hdd/$(hostname)
        fi
        cd /root/usb-hdd/$(hostname)
        rm -f *
        
        /root/host-backup --no-sms
        echo "host-backup ends"
        
        /root/vm-backup --no-sms $VMS_TO_BACKUP
        cd /root

        umount /root/usb-hdd
    else
        echo "Unable to mount partition with label $(hostname)"
    fi    
else
    echo "Set variable VMS_TO_BACKUP in $DIR/config"    
fi    

