#!/bin/bash

param_file=$1
clean=0

if [[ $param_file == *.zip ]]
then
  upd_name=`basename $param_file .zip`
  upd_file=${upd_name}.xsupdate
  
  unzip -d /root $param_file $upd_file
  upd_dir=/root
  clean=1
else
  if [[ $param_file == *.xsupdate ]]
  then
    upd_file=$param_file
    upd_name=`basename ${upd_file} .xsupdate`
    upd=dir=""
    clean=0
  else
    echo "File should be *.zip or *.xsupdate"
    exit
  fi
fi

HOST_UUID=`xe host-list params=uuid | awk 'NF { print $5 }'`

UUID=`xe patch-upload file-name=${upd_dir}/${upd_file}`

if [ $clean == 1 ]
then
  rm -f ${upd_dir}/${upd_file}
fi

xe patch-pool-apply uuid=$UUID

RESULT=`xe patch-list params='after-apply-guidance' uuid=$UUID | awk 'NF { print $4 }'`

case "$RESULT" in

"restartXAPI" )
  echo "Restarting toolstack."
  xe-toolstack-restart
  ;;

"restartHost" )
  echo "Restarting host."
  xe host-disable uuid=$HOST_UUID
  xe host-reboot  uuid=$HOST_UUID
  ;;

* )
  echo "Patch installed."
  ;;

esac
